services:

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: ../api_app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "somedb"

  config1:
    image: mongo:latest
    container_name: config1
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - config1-data:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  config2:
    image: mongo:latest
    container_name: config2
    restart: always
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - config2-data:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  config3:
    image: mongo:latest
    container_name: config3
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network
    volumes:
      - config3-data:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard1a:
    image: mongo:latest
    container_name: shard1a
    restart: always
    ports:
      - "27020:27017"
    networks:
      - app-network
    volumes:
      - shard1a-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard1b:
    image: mongo:latest
    container_name: shard1b
    restart: always
    ports:
      - "27021:27017"
    networks:
      - app-network
    volumes:
      - shard1b-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard1c:
    image: mongo:latest
    container_name: shard1c
    restart: always
    ports:
      - "27022:27017"
    networks:
      - app-network
    volumes:
      - shard1c-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard2a:
    image: mongo:latest
    container_name: shard2a
    restart: always
    ports:
      - "27023:27017"
    networks:
      - app-network
    volumes:
      - shard2a-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard2b:
    image: mongo:latest
    container_name: shard2b
    restart: always
    ports:
      - "27024:27017"
    networks:
      - app-network
    volumes:
      - shard2b-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

  shard2c:
    image: mongo:latest
    container_name: shard2c
    restart: always
    ports:
      - "27025:27017"
    networks:
      - app-network
    volumes:
      - shard2c-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s
    
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    depends_on:
      - config1
      - config2
      - config3
    ports:
      - "27016:27017"
    networks:
      - app-network
    command:
      [
        "mongos",
        "--configdb",
        "config_server/config1:27017,config2:27017,config3:27017",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost:27017", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      start_period: 10s

networks:
  app-network:

volumes:
  config1-data:
  config2-data:
  config3-data:
  shard1a-data:
  shard1b-data:
  shard1c-data:
  shard2a-data:
  shard2b-data:
  shard2c-data:
